### ISSUE TITLE
ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by Nimrod0901** [oneclick/rubyinstaller2#103]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).
```
## What problems are you experiencing?
C:\Users\hasee>gem install jekyll
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: D:/Ruby24/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
D:/Ruby24/bin/ruby.exe -r ./siteconf20180318-5944-8q6cjs.rb extconf.rb
creating Makefile

current directory: D:/Ruby24/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR=" clean
'make' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

current directory: D:/Ruby24/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0/ext/ruby_http_parser
make "DESTDIR="
'make' 不是内部或外部命令，也不是可运行的程序
或批处理文件。

make failed, exit code 1

Gem files will remain installed in D:/Ruby24/lib/ruby/gems/2.4.0/gems/http_parser.rb-0.6.0 for inspection.
Results logged to D:/Ruby24/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/http_parser.rb-0.6.0/gem_make.out
```
## What's the output from `ridk version`?
```
ruby:
  path: D:/Ruby24
  version: 2.4.3
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.3-2
  git_commit: 036e549
msys2:
  path: D:\msys64
  title: MSYS2 64bit
  version: '20170918'
os: Microsoft Windows [版本 10.0.16299.309]
```
## PS
The Chines characters above are similar to 'not an internal or external command nor is it a runnable program Or batch file'
Thank you very much
