### ISSUE TITLE
No rule to make target '<PATH>/ruby.h' when make.exe is present in <OTHER_PATH>/mingw64/bin

### ISSUE THREAD

**Issue by thisismydesign** [oneclick/rubyinstaller2#105]
## What problems are you experiencing?
I'm on a fresh Windows 10 installation trying to set up Ruby and I ran into the issue already mentioned in several places: https://github.com/oneclick/rubyinstaller2/issues/47, https://github.com/gjtorikian/commonmarker/issues/62 but no solution as of yet.

The issue is when trying to install a gem with native extension you get an error originating from `make`:
`make: *** No rule to make target '<PATH>/ruby.h'`

I think I found the cause.

## Steps to reproduce
I installed Ruby via Chocolatey and proceeded to run `ridk install`. I simply pressed enter there which I assume is equivalent to `1 2 3`. This led to the issue (also pointed out here: https://github.com/gjtorikian/commonmarker/issues/62#issuecomment-352276056):
`'make' is not recognized as an internal or external command`
To which the "solution" was (also pointed out in the same thread): https://stackoverflow.com/questions/32127524/how-to-install-and-use-make-in-windows-8-1
In our case: `copy C:\tools\msys64\mingw64\bin\mingw32-make.exe C:\tools\msys64\mingw64\bin\make.exe`
This seem to have fixed `make` not being available but produced the issue described above.

I then found MSYS2 at Chocolatey and followed instructions there with no success: https://chocolatey.org/packages/msys2

Turns out, I had to remove the manually created `make.exe` and it's working fine.

So I suppose there're three possible issues at hand:
1. `ridk install` by itself is flawed?
2. there's no indication that a wrong make executable is used
3. reinstalling MSYS2  or rerunning `ridk install` doesn't get rid of manually placed files

Can't reproduce (1) at this point but hopefully a fresh installation will yield the same behavior. Not sure if there's even something to do about (2) (3).

In any case it's now documented at least.

## What's the output from `ridk version`?
```
---
ruby:
  path: C:/tools/ruby25
  version: 2.5.0
  platform: x64-mingw32
ruby_installer:
  package_version: 2.5.0-2
  git_commit: 9e7814a
msys2:
  path: C:\tools\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: x86_64-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 7.3.0
sh: GNU bash, version 4.4.19(2)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.16299.309]
```
