### ISSUE TITLE
win32ole: WIN32OLERuntimeError raised from ADODB sql query

### ISSUE THREAD

**Issue by bg** [oneclick/rubyinstaller2#108]
## What problems are you experiencing?

While Ruby 2.2 and 2.3 win32ole can handle all valid queries to an MS Access database, under Ruby 2.4, some queries fail with:

```
-e:1:in `method_missing': (in OLE method `Open': ) (WIN32OLERuntimeError)
    OLE error code:80040E14 in Microsoft JET Database Engine
      Internal OLE Automation error
    HRESULT error code:0x80020009
      Exception occurred.
        from -e:1:in `<main>'
```

## Steps to reproduce

I have distilled this test case from a more complex SQL query and a real database to a fairly minimal, reproducible case on a test database which I have attached in [test.zip](https://github.com/oneclick/rubyinstaller2/files/1859749/test.zip). Given a simple db with a single table AvailabilityBlocks with this schema, and containing only 13 records:

```
CREATE TABLE [AvailabilityBlocks]
 (
        [BlockID]                       Long Integer,
        [ResourceID]                    Integer NOT NULL,
        [LocationID]                    Long Integer
);
```

If I specify an SQL query with any "WHERE" clause, under Ruby 2.4, but not earlier versions from Rubyinstaller.org, it triggers the above error, e.g.

```
ruby -rwin32ole -rpp -e "conn=WIN32OLE.new('ADODB.Connection'); conn.open('Provider=Microsoft.Jet.OLEDB.4.0;Data Source=test.mdb'); sql=ARGV.shift; rs=WIN32OLE.new('ADODB.Recordset'); rs.Open(sql, conn); data=rs.GetRows.transpose; conn.close; pp data" "SELECT * FROM AvailabilityBlocks WHERE 1"
```

I expected to see this output instead:

```
[[107508, 26, 14],
 [107513, 26, 16],
 [107518, 26, 20],
 [107523, 26, 14],
 [107544, 26, 14],
 [107561, 21, 1],
 [107574, 21, 1],
 [107587, 21, 13],
 [107592, 21, 13],
 [107609, 36, 9],
 [107622, 28, 8],
 [107639, 28, 12],
 [107652, 28, 16]]
```

### Notes:

- If I drop the WHERE clause entirely, I get the expected output, as shown above.
- Other, more useful queries, like "SELECT * FROM AvailabilityBlocks WHERE ResourceID=21" fail in the same way.
- On the production database, which has many more tables and fields, I first encountered the bug in more complex queries than this, and not all queries would fail:
    - Some fairly complex queries like the following would fail:
        - SELECT * FROM AvailabilityBlocks WHERE ([Begin] <= #2019/04/30 23:59:00#) AND ([End] > #2019/04/30 00:00:00#) AND (ResourceID IN (21)) AND (LocationID <> 0)
    - But if I subtly changed them in some fashion, they would succeed. For example, if I replaced the "(21)" with "(21, -1)" in the above query. I could not determine any pattern to what changes yielded good vs. bad results, and some queries that succeeded on one database would fail on another nearly identical database, and vice versa.

## What's the output from `ridk version`?

I tested on two different systems with different Ruby 2.4 releases, and experience the same bug on both systems and both Ruby releases:

### My current development system

This is the ridk version output from the system on which all of the above output was produced, a 64-bit Windows 10 Pro VM:

```
---
ruby:
  path: C:/Ruby243
  version: 2.4.3
  platform: i386-mingw32
ruby_installer:
  package_version: 2.4.3-2
  git_commit: 036e549
msys2:
  path: C:\msys32
  title: MSYS2 32bit
  version: '20161025'
cc: i686-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 7.3.0
sh: GNU bash, version 4.4.19(2)-release (i686-pc-msys)
os: Microsoft Windows [Version 10.0.16299.309]
```

### My old 32-bit Windows 7 Pro VM

On this system, which has a slightly older version of your Ruby 2.4 kit installed on it, the same behaviours described above occur, both for the successful & failing cases. Similarly, Ruby 2.2 and 2.3 do not have the bug on this test system.

```
---
ruby:
  path: c:/Ruby241
  version: 2.4.1
  platform: i386-mingw32
ruby_installer:
  package_version: 2.4.1-1rc2
  git_commit: 1b324f5
msys2:
  path: c:\msys32
  title: MSYS2 32bit
  version: '20160205'
cc: i686-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 6.3.0
sh: GNU bash, version 4.3.42(5)-release (i686-pc-msys)
```

**Comment by bg** [comment]
I tried also Ruby 2.5.0 and then upon discovering you just released 2.5.1, that version as well. Both fail in the same way.

Here's the latest ridk version output for the most recent version I've tested in which the issue still occurs:

```
---
ruby:
  path: c:/Ruby251
  version: 2.5.1
  platform: i386-mingw32
ruby_installer:
  package_version: 2.5.1-1
  git_commit: 71c9f4e
msys2:
  path: c:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: i686-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 7.3.0
sh: GNU bash, version 4.4.19(2)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.16299.309]
```
