### ISSUE TITLE
Running ridk install doesn't install msys2

### ISSUE THREAD

**Issue by golyalpha** [oneclick/rubyinstaller2#114]
## What problems are you experiencing?
When installing Ruby 2.5.1 (ruby -v >ruby 2.5.1p57 (2018-03-29 revision 63029) [x64-mingw32]), and running `ridk install`, the install fails with
```
MSYS2 could not be found. Please run 'ridk install'
or download and install MSYS2 manually from https://msys2.github.io/
```

## Steps to reproduce
1. Install Ruby 2.5.1
2. run `ridk install`
3. press enter *or* type `1` and press enter

## What's the output from `ridk version`?
```
---
ruby:
  path: C:/Ruby25-x64
  version: 2.5.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.5.1-1
  git_commit: 71c9f4e
sh: GNU bash, version 4.4.19(2)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.17134.48]
```

Current solution is to, of course, install MSYS2 manually, but I feel that that's something ridk install should take care of by itself.
