### ISSUE TITLE
Developing a C extension on Windows 10 make error

### ISSUE THREAD

**Issue by xxninjabunnyxx** [oneclick/rubyinstaller2#117]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
I am trying to develop a C extension on Windows 10 and I get
```
mingw32-make: *** [rc_strdup-x64-mingw32.def] Error 128
``` 

## Steps to reproduce
```
ruby extconf.rb
creating Makefile

make
generating rc_strdup-x64-mingw32.def
      0 [main] sh 13676 sync_with_child: child 9828(0x1D0) died before initialization with status code 0xC0000142
   1139 [main] sh 13676 sync_with_child: *** child state waiting for longjmp
/usr/bin/sh: fork: Resource temporarily unavailable
Makefile:264: recipe for target 'rc_strdup-x64-mingw32.def' failed
mingw32-make: *** [rc_strdup-x64-mingw32.def] Error 128
```
### mkmf.log
```
extconf.h is:
/* begin */
1: #ifndef EXTCONF_H
2: #define EXTCONF_H
3: #endif
/* end */
```

## What's the output from `ridk version`?
```
ridk version
---
ruby:
  path: C:/Ruby25-x64
  version: 2.5.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.5.1-1
  git_commit: 71c9f4e
msys2:
  path: C:\Ruby25-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 7.3.0
sh: GNU bash, version 4.4.19(3)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.17134.112]
```
