### ISSUE TITLE
Ruby is removed from PATH when reinstalling

### ISSUE THREAD

**Issue by orgads** [oneclick/rubyinstaller2#125]
## What problems are you experiencing?
Ruby bin is removed from PATH env variable when reinstalling (or upgrading) it.

## Steps to reproduce
* Install Ruby - It is added to PATH
* Reinstall - It is removed and not re-added.

## What's the output from `ridk version`?
```
---
ruby:
  path: F:/Ruby
  version: 2.4.4
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.4-2
  git_commit: 513abb8
msys2:
  path: F:\msys64
  title: MSYS2 64bit
  version: '20160205'
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 7.3.0
sh: GNU bash, version 4.4.19(3)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 6.1.7601]
```
