### ISSUE TITLE
Letting `ridk` work behind a proxy with a Self Signed Certificate.

### ISSUE THREAD

**Issue by aaroncalderon** [oneclick/rubyinstaller2#126]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
Installing `mingw-w64-x86_64-toolchain` fails due to 'SSL Certificate problem: self signed coertificate in certificate chain'.

## Steps to reproduce

1. Get a job at a company with a corporate proxy that re-encrypts all SSL connections with a self signed certificate,
2. Run `ridk exec pacman -Sy --needed base-devel mingw-w64-x86_64-toolchain`

## What's the output from `ridk version`?

```
 ridk version
---
ruby:
  path: C:/Ruby25-x64
  version: 2.5.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.5.1-2
  git_commit: 1dfa3f5
msys2:
  path: C:\dev\prd\msys64
  title: MSYS2 64bit
  version: '20180531'
sh: GNU bash, version 4.4.19(3)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.16299.611]
```

## Additional Information

I have configured many other modern tools (e.g. ruby, git, vagrant, npm, node.js, [wget](https://stackoverflow.com/questions/22282013/how-to-use-wget-with-ssl-certificate/50494174#50494174)) to trust the self signed certificate to ensure all connections stay secure.

However, I have not been able to figure out how `pacman` should be configured to use this, or is it `msys2` that needs to be configured?

Any help is appreciated.

## Troubleshooting steps so far

I have added the public self signed certificate to: `C:\dev\prd\msys64\usr\ssl\certs\`, but has made no difference.

Sould I add the certificate hash to `C:\dev\prd\msys64\usr\ssl\certs\ca-bundle.crt` or  `C:\dev\prd\msys64\usr\ssl\certs\ca-bundle.trust.crt`?
