### ISSUE TITLE
[2.5.3] rake's executable "rake" conflicts with C:/Ruby25-x64/bin/rake

### ISSUE THREAD

**Issue by janpio** [oneclick/rubyinstaller2#134]
First, let me start with how much I ❤️ your work. I wish your installers would have been available and as stable as they are now 15 years back, when I decided what programming language to learn. 🌈 

---

## What problems are you experiencing?

While trying to add Windows testing for [bundler](https://github.com/bundler/bundler) I encountered a strange error with RubyInstaller's 2.5.x: https://github.com/bundler/bundler/issues/6903

I could reproduce the problem out of bundler context as well:

```
PS C:\Projects> gem install rake
Fetching: rake-12.3.2.gem (100%)
rake's executable "rake" conflicts with C:/Ruby25-x64/bin/rake
Overwrite the executable? [yN]  n
ERROR:  Error installing rake:
        "rake" from rake conflicts with C:/Ruby25-x64/bin/rake
```

When I reply with `y`, the content of `C:/Ruby25-x64/bin/rake` is modified:

```patch
1,9c1
< :""||{ ""=> %q<-*- ruby -*-
< @"%~dp0ruby" -x "%~f0" %*
< @exit /b %ERRORLEVEL%
< };{#
< bindir="${0%/*}" #
< exec "$bindir/ruby" "-x" "$0" "$@" #
< >,
< }
< #!/usr/bin/env ruby
---
> #!C:/Ruby25-x64/bin/ruby.exe
```

Then everything works fine.

But as in bundler's context it is not possible to reply to the prompt at all (as it is running on CI, via a `rake` task, this is not a usable workaround there.

Is this intended behavior?
Is this prompt only caused by the difference in the `bin/rake` file?

I looked a bit, but couldn't find where/why this `rake` file was added in 2.5.x - in 2.4.x I don't seem to have the problem described above.

I also have the same problem on CI services as for example Azure Pipelines, this does not only affect my local environment. There the version installed seems to be just 2.5.0.

## Steps to reproduce

1. Install a 2.5.x ruby, e.g. https://github.com/oneclick/rubyinstaller2/releases/download/rubyinstaller-2.5.3-1/rubyinstaller-devkit-2.5.3-1-x64.exe
2. Run `gem install rake`
3. Observe the `rake's executable "rake" conflicts with ...` output

## What's the output from `ridk version`?

```
PS C:\Projects> ridk version
---
ruby:
  path: C:/Ruby25-x64
  version: 2.5.3
  platform: x64-mingw32
ruby_installer:
  package_version: 2.5.3-1
  git_commit: 16e7aa4
msys2:
  path: C:\msys64
  title: MSYS2 64bit
  version: '20180531'
cc: x86_64-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 8.2.1 20181214
sh: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.17134.523]
```
