### ISSUE TITLE
Ruby 2.6 JIT - Impossible to use JIT

### ISSUE THREAD

**Issue by D3nX** [oneclick/rubyinstaller2#135]
Hello ! I have a problem with Ruby 2.6 JIT on Windows 7 (64-bit).

## What problems are you experiencing?
Okay so, I'm just trying to use JIT with a simple console program. But when I'm trying compiling the program it output me :
```
MJIT: Failed to create process: No such file or directory
MJIT warning: Making precompiled header failed on compilation. Stopping MJIT worker...
```
And the program run normally, but without JIT.

## Steps to reproduce
- Create a folder
- Add a new Ruby file (I called it app.rb)
- Write this code inside the Ruby file :
```ruby
loop do
	puts "Hello World!"
	gets
end
```
- Finally open a cmd console and write ``ruby --jit-verbose=1 app.rb``

## What's the output from `ridk version`?
The output is that :
```
---
ruby:
  path: C:/Ruby26-x64
  version: 2.6.0
  platform: x64-mingw32
ruby_installer:
  package_version: 2.6.0-1
  git_commit: 7688b64
msys2:
  path: C:\Ruby26-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 8.2.1 20181214
sh: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [version 6.1.7601]
```

<b>Thank you for your help because I really need JIT, I'm making a real time strategy game and it would improve the game performance by a lot ^^</b>
