### ISSUE TITLE
Unable to handle a directory with a Russian name

### ISSUE THREAD

**Issue by ashmaroli** [oneclick/rubyinstaller2#143]
## What problems are you experiencing?

I'm unable to work in a directory with a Russian name.
I'm not sure if the issue is with Ruby itself or my installation on Windows 7

## Steps to reproduce

1. Create a directory named `Евгений`
2. cd into that directory and fire up `irb`
```
cd Евгений
irb
```
3. Get current path with `Dir.pwd`
```
irb(main):001:0> Dir.pwd
=> "C:/Demo/???????"
```

## What's the output from `ridk version`?
```
ruby:
  path: D:/Ruby2.4-x64
  version: 2.4.5
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.5-1
  git_commit: 16e7aa4
msys2:
  path: D:\Ruby2.4-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 8.3.0
sh: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 6.1.7601]
```
