### ISSUE TITLE
gem install tiny_tds --platform ruby

### ISSUE THREAD

**Issue by vais** [oneclick/rubyinstaller2#146]
This project is for Ruby version 2.4 and newer.
For Ruby versions < 2.4 please file an issue [here]( https://github.com/oneclick/rubyinstaller/issues/new ).

## What problems are you experiencing?
I successfully installed tiny_tds gem with `gem install tiny_tds --platform ruby` and was able to use it, but after moving the installation to another computer that does not have msys64, `require 'tiny_tds'` no longer worked. I have done this with multiple other C extension gems in the past, and this is the first one that has this problem.

I narrowed down the problem to simply renaming the msys64 directory on my computer. Using the trusty sysinternals process monitor utility I was able to see that ruby is looking for `libsybdb-5.dll` in the ruby `bin` directory. Manually copying `libsybdb-5.dll` from `msys64\mingw32\bin` to `utilities\ruby\bin` solves the problem.

I would like to help tiny_tds project resolve this issue, but I don't know where to begin, and I'm posting this issue here because it looks like on the tiny_tds side there is not much expertise with building gems to work with rubyinstaller2 - i.e. their pre-built tiny_tds fat gem installed by default (without `--platform ruby`) does not work at all.

Is there a way to modify tiny_tds to make it vendor this dll as it does with the rest of freetds? I mean it supposedly statically links freetds into their C extension, but somehow this one dll is left out? Thanks in advance for any pointers...

## Steps to reproduce
```
gem install tiny_tds --platform ruby
ruby -e "require 'tiny_tds'" #=> no problem
move C:\msys64 C:\x-msys64
ruby -e "require 'tiny_tds'"
C:/Ruby/rubyinstaller-2.4.5-1-x86/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': 126: The specified module could not be found.   - C:/Ruby/rubyinstaller-2.4.5-1-x86/lib/ruby/gems/2.4.0/gems/tiny_tds-2.1.2/lib/tiny_tds/tiny_tds.so (LoadError)
        from C:/Ruby/rubyinstaller-2.4.5-1-x86/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby/rubyinstaller-2.4.5-1-x86/lib/ruby/gems/2.4.0/gems/tiny_tds-2.1.2/lib/tiny_tds.rb:46:in `rescue in block in <top (required)>'
        from C:/Ruby/rubyinstaller-2.4.5-1-x86/lib/ruby/gems/2.4.0/gems/tiny_tds-2.1.2/lib/tiny_tds.rb:43:in `block in <top (required)>'
        from C:/Ruby/rubyinstaller-2.4.5-1-x86/lib/ruby/gems/2.4.0/gems/tiny_tds-2.1.2/lib/tiny_tds.rb:37:in `block in <top (required)>'
        from C:/Ruby/rubyinstaller-2.4.5-1-x86/lib/ruby/gems/2.4.0/gems/tiny_tds-2.1.2/lib/tiny_tds.rb:42:in `<top (required)>'
        from C:/Ruby/rubyinstaller-2.4.5-1-x86/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby/rubyinstaller-2.4.5-1-x86/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby/rubyinstaller-2.4.5-1-x86/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from -e:1:in `<main>'
```

## What's the output from `ridk version`?
```
---
ruby:
  path: C:/Ruby/rubyinstaller-2.4.5-1-x86
  version: 2.4.5
  platform: i386-mingw32
ruby_installer:
  package_version: 2.4.5-1
  git_commit: 16e7aa4
msys2:
  path: c:\msys64
  title: MSYS2 64bit
  version: '20161025'
cc: i686-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 7.2.0
sh: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.17134.648]
```
