### ISSUE TITLE
ridk fails to detect MSYS2.

### ISSUE THREAD

**Issue by asm256** [oneclick/rubyinstaller2#154]
## What problems are you experiencing?
MSYS2 installed, but ridk says "MSYS2 seems to be unavailable"

## Steps to reproduce
1. uninstall msys2
2. Register garbage in the registry.
![image](https://user-images.githubusercontent.com/660363/63563011-9b246580-c59a-11e9-8225-80e13a444118.png)

3. install msys2
4. `ridk version` or `ridk install 1`

## What's the output from `ridk version`?

```
C:\Users\>ridk version
---
ruby:
  path: F:/ruby_installer/Ruby26-x64
  version: 2.6.3
  platform: x64-mingw32
ruby_installer:
  package_version: 2.6.3-1
  git_commit: 779b05c
os: Microsoft Windows [Version 6.1.7601]
```
