### ISSUE TITLE
 How do I change the MSYS2 directory?

### ISSUE THREAD

**Issue by keito940** [oneclick/rubyinstaller2#157]
## What problems are you experiencing?

I have MSYS2 installed on my computer. I want to delete DevKit that was installed when Rubyinstaller was installed and specify DevKit on the computer.
What should I do because it was not written in the manual?

## What's the output from `ridk version`?
```
ruby:
  path: C:/Ruby25-x64
  version: 2.5.5
  platform: x64-mingw32
ruby_installer:
  package_version: 2.5.5-1
  git_commit: ef6f204
msys2:
  path: C:\Ruby25-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 8.3.0
sh: GNU bash, バージョン 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.18362.295]
```
