### ISSUE TITLE
irb history doesn't work on RubyInstaller-2.6.x

### ISSUE THREAD

**Issue by larskanis** [oneclick/rubyinstaller2#158]
## What problems are you experiencing?
When running irb of a fresh install of ruby-2.6.4, it doesn't keep the readline history. So commands entered in one irb session are lost of irb is started a second time. It however works in ruby-2.5.6.

## Steps to reproduce
* Install ruby-2.6.4
* run `irb` in `cmd` and enter some lines
* run `irb` a second time and try to use cursor keys to select a line from the previous session

## What's the output from `ridk version`?
```
ruby:
  path: C:/Ruby26-x64
  version: 2.6.4
  platform: x64-mingw32
ruby_installer:
  package_version: 2.6.4-1
  git_commit: 8f0b0b4
msys2:
  path: C:\Ruby26-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 9.2.0
sh: GNU bash, Version 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.17763.720]
```

The content of `irb.cmd` changed in ruby-2.6, so that [this patch](https://github.com/oneclick/rubyinstaller2/blob/master/recipes/sandbox/20-extend-irb.rake) needs to be updated.
