### ISSUE TITLE
Undefined reference to `__chk_fail' and `__memcpy_chk' when compiling extensions (+solution)

### ISSUE THREAD

**Issue by native-api** [oneclick/rubyinstaller2#168]
## What problems are you experiencing?
Subj.

## Steps to reproduce
```
ruby 2.6.3p62 (2019-04-16 revision 67580) [x64-mingw32]

> gem install libyajl2
Fetching libyajl2-2.0.0.gem
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing libyajl2:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/libyajl2-2.0.0/ext/libyajl2
C:/Ruby26-x64/bin/ruby.exe -I C:/Ruby26-x64/lib/ruby/2.6.0 -r ./siteconf20200207-8896-s6oj5v.rb extconf.rb
creating Makefile
/c/Ruby26-x64/lib/ruby/gems/2.6.0/gems/libyajl2-2.0.0/ext/libyajl2
extconf.rb:105:in `makemakefiles': unhandled exception
        from extconf.rb:139:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/libyajl2-2.0.0 for inspection.
Results logged to C:/Ruby26-x64/lib/ruby/gems/2.6.0/extensions/x64-mingw32/2.6.0/libyajl2-2.0.0/gem_make.out


> type c:\Ruby26-x64\lib\ruby\gems\2.6.0\gems\libyajl2-2.0.0\ext\libyajl2\make.out
compiling yajl.c
compiling yajl_alloc.c
compiling yajl_buf.c
compiling yajl_encode.c
compiling yajl_gen.c
compiling yajl_lex.c
compiling yajl_parser.c
compiling yajl_tree.c
compiling yajl_version.c
linking shared-object libyajl.so
C:/Ruby26-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: yajl_gen.o:yajl_gen.c:(.text+0x591): undefined reference to `__chk_fail'
C:/Ruby26-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: yajl_gen.o:yajl_gen.c:(.text+0x87f): undefined reference to `__memcpy_chk'
C:/Ruby26-x64/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/9.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: yajl_gen.o:yajl_gen.c:(.text+0x8f1): undefined reference to `__chk_fail'
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:261: libyajl.so] Error 1
```

## What's the output from `ridk version`?

```
---
ruby:
  path: C:/Ruby26-x64
  version: 2.6.3
  platform: x64-mingw32
ruby_installer:
  package_version: 2.6.3-1
  git_commit: 779b05c
msys2:
  path: C:\Ruby26-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 9.2.0
sh: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 6.1.7601]
```

---

To fix this, you need to add `-lssp` to `LDFLAGS` as per https://github.com/msys2/MINGW-packages/issues/5868#issuecomment-544107564. I couldn't find where to put this step into this repo though.

```
--- C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/rbconfig.rb_	Fri Feb 07 05:24:17 2020
+++ C:/Ruby26-x64/lib/ruby/2.6.0/x64-mingw32/rbconfig.rb	Fri Feb 07 04:57:45 2020
@@ -181,7 +181,7 @@
   CONFIG["CXX"] = "x86_64-w64-mingw32-g++"
   CONFIG["OBJEXT"] = "o"
   CONFIG["CPPFLAGS"] = "-D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0600 -D__MINGW_USE_VC2005_COMPAT $(DEFS) $(cppflags)"
-  CONFIG["LDFLAGS"] = "-L. -pipe -s"
+  CONFIG["LDFLAGS"] = "-L. -pipe -s -lssp"
   CONFIG["CFLAGS"] = "-O3 -fno-fast-math"
   CONFIG["CC"] = "x86_64-w64-mingw32-gcc"
   CONFIG["target_os"] = "mingw32"
```
