### ISSUE TITLE
rubyinstaller-devkit-2.6.6-1-x64.exe reinstalling does not request a installation path

### ISSUE THREAD

**Issue by dinya** [oneclick/rubyinstaller2#175]
I install Ruby with [rubyinstaller-devkit-2.6.6-1-x64.exe](https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.6.6-1/rubyinstaller-devkit-2.6.6-1-x64.exe) under Windows 10.

Uninstall procedure remove Ruby itself but it doesn't remove msys2. Moreover the Installer doesn't edit registry. Thus after starting the re-installation the Installer doesn't request the installation path because ``HKEY_CURRENT_USER\Software\RubyInstaller\MRI\2.6.6 -> InstallLocation`` still exists and installs Ruby+MSYS2 in the old location.

Deleting the key ``HKEY_CURRENT_USER\Software\RubyInstaller\MRI\2.6.6`` allows to select the installation path.

Output from `ridk version`:

```
---
ruby:
  path: D:/00data/opt/Ruby26-x64
  version: 2.6.6
  platform: x64-mingw32
ruby_installer:
  package_version: 2.6.6-1
  git_commit: eb60b1c
msys2:
  path: D:\00data\opt\Ruby26-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 9.3.0
sh: GNU bash, версия 4.4.23(2)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.18363.900]
```
