### ISSUE TITLE
error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown

### ISSUE THREAD

**Issue by jwalkerbg** [oneclick/rubyinstaller2#184]
## What problems are you experiencing?

I get errors when executing `ridk install`:
'error: mingw32: key "4A6129F4E4B84AE46ED7F635628F528CF3053E04" is unknown'

## Steps to reproduce

1. Download rubyinstaller, par example https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-2.6.6-1/rubyinstaller-devkit-2.6.6-1-x64.exe
2. Run installer.
3. Ruby installs correctly, MSYS2 installation begins.
4. The above error occurs.

## What's the output from `ridk version`?

```
C:\Users\imc>ridk version
---
ruby:
  path: C:/Ruby26-x64
  version: 2.6.6
  platform: x64-mingw32
ruby_installer:
  package_version: 2.6.6-1
  git_commit: eb60b1c
msys2:
  path: C:\Ruby26-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev1, Built by MSYS2 project) 9.3.0
sh: GNU bash, version 4.4.23(2)-release (x86_64-pc-msys)
os: |-
  Active code page: 65001

  Microsoft Windows [Version 10.0.19041.388]`

```

## Comments

This issue is probably result of changes described here : https://www.msys2.org/news/#2020-06-29-new-packagers. I suppose that new packages should be generated that will include new keys.
