### ISSUE TITLE
ridk install fails

### ISSUE THREAD

**Issue by Regenhardt** [oneclick/rubyinstaller2#196]
## What problems are you experiencing?

Trying to install ruby, `ridk install 1 3` fails because of unknown signature:

```
PS C:\Windows\system32> ridk install 1 3
 _____       _           _____           _        _ _         ___
|  __ \     | |         |_   _|         | |      | | |       |__ \
| |__) |   _| |__  _   _  | |  _ __  ___| |_ __ _| | | ___ _ __ ) |
|  _  / | | | '_ \| | | | | | | '_ \/ __| __/ _` | | |/ _ \ '__/ /
| | \ \ |_| | |_) | |_| |_| |_| | | \__ \ || (_| | | |  __/ | / /_
|_|  \_\__,_|_.__/ \__, |_____|_| |_|___/\__\__,_|_|_|\___|_||____|
                    __/ |           _
                   |___/          _|_ _  __   | | o __  _| _     _
                                   | (_) |    |^| | | |(_|(_)\^/_>

> sh -lc true
MSYS2 seems to be properly installed
Install MSYS2 and MINGW development toolchain ...
> pacman -S --needed --noconfirm autoconf autogen automake-wrapper diffutils file gawk grep libtool m4 make patch pkg-config sed texinfo texinfo-tex wget mingw-w64-x86_64-binutils mingw-w64-x86_64-crt-git mingw-w64-x86_64-gcc mingw-w64-x86_64-gcc-libs mingw-w64-x86_64-headers-git mingw-w64-x86_64-libmangle-git mingw-w64-x86_64-libwinpthread-git mingw-w64-x86_64-make mingw-w64-x86_64-pkg-config mingw-w64-x86_64-tools-git mingw-w64-x86_64-winpthreads-git
error: mingw32: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: mingw64: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: msys: signature from "David Macek <david.macek.0@gmail.com>" is unknown trust
error: database 'mingw32' is not valid (invalid or corrupted database (PGP signature))
error: database 'mingw64' is not valid (invalid or corrupted database (PGP signature))
error: database 'msys' is not valid (invalid or corrupted database (PGP signature))
Install MSYS2 and MINGW development toolchain failed
Traceback (most recent call last):
        16: from C:/Ruby27-x64/bin/ridk.cmd:39:in `<main>'
        15: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/ridk.rb:14:in `run!'
        14: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/ridk.rb:99:in `install'
        13: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/components_installer.rb:35:in `install'
        12: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:110:in `top_level'
        11: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:125:in `run_with_threads'
        10: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block in top_level'
         9: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `each'
         8: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:116:in `block (2 levels) in top_level'
         7: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/application.rb:160:in `invoke_task'
         6: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:188:in `invoke'
         5: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `invoke_with_call_chain'
         4: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:199:in `synchronize'
         3: from C:/Ruby27-x64/lib/ruby/gems/2.7.0/gems/rake-13.0.1/lib/rake/task.rb:219:in `block in invoke_with_call_chain'
         2: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/components/03_dev_tools.rb:44:in `execute'
         1: from C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/msys2_installation.rb:198:in `with_msys_apps_enabled'
C:/Ruby27-x64/lib/ruby/site_ruby/2.7.0/ruby_installer/runtime/components/03_dev_tools.rb:51:in `block in execute': pacman failed (RuntimeError)
```

## Steps to reproduce

Just start the ruby installer, then have it run risk install at the end. 

## What's the output from `ridk version`?

```
PS C:\Windows\system32> ridk version
---
ruby:
  path: C:/Ruby27-x64
  version: 2.7.2
  platform: x64-mingw32
  cc: x86_64-w64-mingw32-gcc.exe (Rev1, Built by MSYS2 project) 10.2.0
ruby_installer:
  package_version: 2.7.2-1
  git_commit: df3bebb
msys2:
  path: C:\Ruby27-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev3, Built by MSYS2 project) 10.2.0
sh: GNU bash, version 4.4.23(2)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19042.572]
```
