### ISSUE TITLE
Installer without Devkit doesn't detect existing MSYS2 installation from much older set up

### ISSUE THREAD

**Issue by ashmaroli** [oneclick/rubyinstaller2#201]
## What problems are you experiencing?

When I run `ridk enable`, I get an error message requesting to run `ridk install`

## Steps to reproduce

I can't vouch the following to be the actual steps to reproduce the issue.
Nevertheless, this is how things are at my end.

- Install Ruby 2.4.5 x64 with Devkit (yep pretty old) (to non-standard path: `D:\Rubies\Ruby2.4-x64`)
- Run `ridk install` with default options. (to non-standard path: `D:\Rubies\Ruby2.4-x64\msys64`)
- Install Ruby 2.5.8 x64 **without Devkit** (since MSYS2 was previously installed) (to non-standard path: `D:\Ruby2.5-x64`)
- Skip `ridk install`.
- Run `ridk enable`

## What's the output from `ridk version`?

```
ruby:
  path: D:/Ruby2.5-x64
  version: 2.5.8
  platform: x64-mingw32
  cc: x86_64-w64-mingw32-gcc.exe (Rev1, Built by MSYS2 project) 10.2.0
ruby_installer:
  package_version: 2.5.8-2
  git_commit: 6bb10fc
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 8.3.0
sh: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 6.1.7601]
```

## Additional context

Switch to old Ruby version:
```
ridk use list

Disable MSYS2 variables for path D:\Rubies\Ruby2.4-x64\msys64
MSYS2 could not be found. Please run 'ridk install'
or download and install MSYS2 manually from https://msys2.github.io/
1 - D:/Rubies/Ruby2.4-x64       ruby 2.4.5p335 (2018-10-18 revision 65137) [x64-mingw32]
2 - D:/Ruby2.5-x64      ruby 2.5.8p224 (2020-03-31 revision 67882) [x64-mingw32]
```
```
ridk use 1

Disable MSYS2 variables for path D:\Rubies\Ruby2.4-x64\msys64
MSYS2 could not be found. Please run 'ridk install'
or download and install MSYS2 manually from https://msys2.github.io/
Disable D:/Rubies/Ruby2.4-x64
Disable D:/Rubies/Ruby2.4-x64
Disable D:/Ruby2.5-x64
```
```
ridk use 1

Disable MSYS2 variables for path D:\Rubies\Ruby2.4-x64\msys64
'ruby' is not recognized as an internal or external command,
operable program or batch file.
Disable D:/Rubies/Ruby2.4-x64
Disable D:/Ruby2.5-x64
Enable D:/Rubies/Ruby2.4-x64
```
```
ridk version
---
ruby:
  path: D:/Rubies/Ruby2.4-x64
  version: 2.4.5
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.5-1
  git_commit: 16e7aa4
msys2:
  path: D:\Rubies\Ruby2.4-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 8.3.0
sh: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 6.1.7601]
```
