### ISSUE TITLE
RubyGems documentation server doesn't work for generated documentation

### ISSUE THREAD

**Issue by luislavena** [oneclick/rubyinstaller2#21]
## What problems are you experiencing?

Attempted to use *RubyGems Documentation Server* and access the RDoc generated for `rake` gem with issues.

## Steps to reproduce

- Clean installation of RubyInstaller
- Inside cmd, install `rake` gem: `gem install rake --document`
- Fire up *RubyGems Documentation Server*
- From the list of gems, click on `[rdoc]` link
- First page of documentation loads, but no styles or images
- Click on any of the elements results in 404

## What's the output from `ridk version`?

```yaml
---
ruby:
  path: C:/Ruby24-x64
  version: 2.4.0
  platform: x64-mingw32
ruby_installer:
  version: 2.4.0-8
  git_commit: c55856f
```

## Screenshots

![1](https://cloud.githubusercontent.com/assets/4182/23483354/5a0235ee-feb1-11e6-8b3c-da89e2bf1a7b.PNG)
![2](https://cloud.githubusercontent.com/assets/4182/23483362/5d8509da-feb1-11e6-96a8-0a6a0658e336.PNG)
![3](https://cloud.githubusercontent.com/assets/4182/23483366/6000fe94-feb1-11e6-9918-ddc0a6bd9fcb.PNG)
