### ISSUE TITLE
MSYS2's pkgconf v. ridk's pkg-config

### ISSUE THREAD

**Issue by i-s-o** [oneclick/rubyinstaller2#222]
## What problems are you experiencing?
Running `ridk` removes `pkgconf` (and installs `pkg-config`). Later on, this created some issues while compiling a project.

See relevant discussion here:
https://github.com/msys2/MINGW-packages/issues/7263

## Steps to reproduce
* Install a recent version of MSYS2 (post-November 22).
* Apply latest updates.
* Install Ruby (non-devkit, tested with rubyinstaller-2.7.3-1-x64.exe from AppVeyor).
* Run `ridk install`.

## What's the output from `ridk version`?
```
C:\Users\WDAGUtilityAccount>ridk version
---
ruby:
  path: C:/tools/Ruby27-x64
  version: 2.7.3
  platform: x64-mingw32
  cc: x86_64-w64-mingw32-gcc.exe (Rev9, Built by MSYS2 project) 10.2.0
ruby_installer:
  package_version: 2.7.3-1
  git_commit: ee9dfe3
msys2:
  path: C:\tools\msys64
cc: x86_64-w64-mingw32-gcc (Rev10, Built by MSYS2 project) 10.2.0
sh: GNU bash, version 5.1.4(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19041.928]
```

## Output from `ridk install`
```
Which components shall be installed? If unsure press ENTER [1,3] 1

> sh -lc true
MSYS2 seems to be properly installed

   1 - MSYS2 base installation
   2 - MSYS2 system update (optional)
   3 - MSYS2 and MINGW development toolchain

Which components shall be installed? If unsure press ENTER [] 3

> sh -lc true
MSYS2 seems to be properly installed
Install MSYS2 and MINGW development toolchain ...
... skipped all packages, except:
resolving dependencies...
looking for conflicting packages...
:: mingw-w64-x86_64-pkg-config and mingw-w64-x86_64-pkgconf are in conflict. Remove mingw-w64-x86_64-pkgconf? [Y/n]
:: pkg-config and pkgconf are in conflict. Remove pkgconf? [Y/n]

Packages (4) mingw-w64-x86_64-pkgconf-1.7.3-6 [removal]  pkgconf-1.7.3-2 [removal]
             mingw-w64-x86_64-pkg-config-0.29.2-3  pkg-config-0.29.2-4

Total Download Size:   0.45 MiB
Total Installed Size:  1.87 MiB
Net Upgrade Size:      1.15 MiB

:: Proceed with installation? [Y/n]
:: Retrieving packages...
 mingw-w64-x86_64-pkg-config-0.29.2-3-any    262.8 KiB   494 KiB/s 00:01 [#######################################] 100%
 pkg-config-0.29.2-4-x86_64                  202.0 KiB  13.2 MiB/s 00:00 [#######################################] 100%
(2/2) checking keys in keyring                                           [#######################################] 100%
(2/2) checking package integrity                                         [#######################################] 100%
(2/2) loading package files                                              [#######################################] 100%
(2/2) checking for file conflicts                                        [#######################################] 100%
(4/4) checking available disk space                                      [#######################################] 100%
:: Processing package changes...
(1/2) removing mingw-w64-x86_64-pkgconf                                  [#######################################] 100%
(2/2) removing pkgconf                                                   [#######################################] 100%
(1/2) installing pkg-config                                              [#######################################] 100%
(2/2) installing mingw-w64-x86_64-pkg-config                             [#######################################] 100%
Install MSYS2 and MINGW development toolchain succeeded
```
