### ISSUE TITLE
rbs and typeprof commands are unavailable by default

### ISSUE THREAD

**Issue by JunichiIto** [oneclick/rubyinstaller2#231]
## What problems are you experiencing?

I installed Ruby 3.0.1 with RubyInstaller, but `rbs` and `typeprof` commands are not found in my cmd.exe. They are available by default in Mac environment which I installed with rbenv. So I had to run `gem install rbs` and `gem install typeprof`, then `rbs` and `typeprof` became available. (They appeared in `C:\Ruby30-x64\bin`) But they should be available by default.

## Steps to reproduce

(I described above.)

## What's the output from `ridk version`?

```
C:\Ruby30-x64\bin>ridk version
bash.exe: warning: could not find /tmp, please create!
---
ruby:
  path: C:/Ruby30-x64
  version: 3.0.1
  platform: x64-mingw32
  cc: x86_64-w64-mingw32-gcc.exe (Rev9, Built by MSYS2 project) 10.2.0
ruby_installer:
  package_version: 3.0.1-1
  git_commit: '8225034'
msys2:
  path: C:\Ruby30-x64\msys64
cc: x86_64-w64-mingw32-gcc (Rev6, Built by MSYS2 project) 10.2.0
sh: GNU bash, バージョン 5.1.4(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19042.804]
```
