### ISSUE TITLE
'jekyll' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by kcindric** [oneclick/rubyinstaller2#241]
## What problems are you experiencing?
`'jekyll' is not recognized as an internal or external command,
operable program or batch file.` although I restarted my system and Jekyll is properly installed:

![image](https://user-images.githubusercontent.com/44549361/126893862-4cb4ac66-726e-4052-b9e8-5dad0170eebf.png)

## Steps to reproduce
Install `Ruby+DevKit` and after that `gem install jekyll bundler`. Close `cmd` and restart system. When I run `jekyll -v` I get the message above.

Tried reinstalling with `gem install jekyll bundler` but everything is already installed.

## What's the output from `ridk version`?

```
ruby:
  path: C:/Ruby30-x64
  version: 3.0.2
  platform: x64-mingw32
  cc: gcc.exe (Rev5, Built by MSYS2 project) 10.3.0
ruby_installer:
  package_version: 3.0.2-1
  git_commit: 80c9ca9
msys2:
  path: C:\msys64
sh: GNU bash, version 4.4.23(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19042.1110]
```
