### ISSUE TITLE
Ruby 3.1 gem command on Windows seems noticeably slower than Ruby 3.0

### ISSUE THREAD

**Issue by johnnyshields** [oneclick/rubyinstaller2#264]
## What problems are you experiencing?

Installed `RubyInstaller 3.1.1-1`. Running `gem install` and `bundle install` seems noticeably slower than on Ruby 3.0. Even `gem update --system` is very slow.

## Steps to reproduce

As per above.

## What's the output from `ridk version`?

```
---
ruby:
  path: C:/ruby31
  version: 3.1.1
  platform: x64-mingw-ucrt
  cc: gcc.exe (Rev9, Built by MSYS2 project) 11.2.0
ruby_installer:
  package_version: 3.1.1-1
  git_commit: d9d39f1
msys2:
  path: C:\ruby31\msys64
cc: gcc (Rev10, Built by MSYS2 project) 11.2.0
sh: GNU bash, version 5.1.16(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.22000.556]
```
