### ISSUE TITLE
Needs windows debug symbols!

### ISSUE THREAD

**Issue by ariccio** [oneclick/rubyinstaller2#272]
## What problems are you experiencing?
The version of ruby installed with ruby installer does not include microsoft-tooling compatible debug symbols.

I'm not entirely familiar with the Ruby build infrastructure on windows, but it seems that the version of ruby installed with rubyinstaller2 is built with GCC? If so, and there's no option to build with MSVC, I think *you can close this issue* since it doesn't seem like gcc has any support for the necessary debug symbol generation. If there is an option to build with MSVC, I don't see any documentation (I don't even know how that would interact with MSYS2?!?).

## Steps to reproduce
Try to profile or debug the interpreter on windows, see no symbol information.

## What's the output from `ridk version`?
```
---
ruby:
  path: C:/Ruby31-x64
  version: 3.1.1
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.1.1-1
  git_commit: d9d39f1
msys2:
  path: C:\Ruby31-x64\msys64
cc: gcc (Rev9, Built by MSYS2 project) 11.2.0
sh: GNU bash, version 5.1.8(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19044.1645]

```
