### ISSUE TITLE
404 Not Found for all 2019 MSYS2 urls

### ISSUE THREAD

**Issue by BinToss** [oneclick/rubyinstaller2#303]
## What problems are you experiencing?
All three options for `ruby install` fail because https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20190524.exe is no longer available.
[Search in the parent directory for available redistributions](https://repo.msys2.org/distrib/x86_64).
![image](https://user-images.githubusercontent.com/7243190/190069357-e3ac3d63-2c90-4dc8-a912-348fdf31eb63.png)

## Steps to reproduce
When MSYS2 is not present...

run `ruby install`
enter any option

alternatively, attempt to access the URL directly
https://repo.msys2.org/distrib/x86_64/msys2-x86_64-20190524.exe

## What's the output from `ridk version`?
```yml
ruby:
  path: C:/Apps/Ruby
  version: 3.1.2
  platform: x64-mingw-ucrt
  cc: gcc.exe (Rev10, Built by MSYS2 project) 11.2.0
ruby_installer:
  package_version: 3.1.2-1
  git_commit: 17502f9
os: Microsoft Windows [Version 10.0.22000.856]
```
