### ISSUE TITLE
Permissions on install directory exclude Administrator

### ISSUE THREAD

**Issue by larskanis** [oneclick/rubyinstaller2#317]
## What problems are you experiencing?

RubyInstaller-3.1.3, 3.0.5 and 2.7.7 restrict the permissions on the install directory, so that only the creator can change it. Unfortunately this also excludes Administrator permissions, so that an Admin can not change anything to the folder, which is unexpected.

Instead he has to run `takeown` on the folder to get access to it.

## Steps to reproduce

* Install RubyInstaller-3.1.3 to C:/Ruby31-x64
* Inspect folder permissions per: `icacls C:/Ruby31-x64` . It looks like:
```sh
C:\Ruby31-x64 COMCARD\Kanis:(F)
              ERSTELLER-BESITZER:(OI)(CI)(IO)(F)
              VORDEFINIERT\Benutzer:(OI)(CI)(RX)
```
but it shoud include
```
              VORDEFINIERT\Administratoren:(OI)(CI)(F)
```

## What's the output from `ridk version`?
```
---
ruby:
  path: C:/Ruby32-x64
  version: 3.2.0
  platform: x64-mingw-ucrt
  cc: gcc.exe (Rev3, Built by MSYS2 project) 12.2.0
ruby_installer:
  package_version: head
  git_commit: beefff7
msys2:
  path: C:\msys64
cc: gcc (Rev6, Built by MSYS2 project) 12.2.0
sh: GNU bash, version 5.2.9(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.14393]
```
