### ISSUE TITLE
Issues with installing jekyll

### ISSUE THREAD

**Issue by episanty** [oneclick/rubyinstaller2#324]
## What problems are you experiencing?
I am consistently failing to install jekyll.

## Steps to reproduce
Running on Windows 10 Enterprise, version 21H2, build 19044.2364.

I followed the steps on https://jekyllrb.com/docs/installation/windows/
 - Downloaded rubyinstaller-devkit-3.1.3-1-x64.exe from https://rubyinstaller.org/downloads/
 - Ran the installer using the standard options
 - Restarted the computer
 - On a fresh PowerShell, ran `gem install bundler` -- this works fine
 - Then, ran `gem install jekyll`

This produces the output below, the highlights from which are

> ERROR:  Error installing jekyll:
>        ERROR: Failed to build gem native extension.

Nothing I try seems to change it. Full output:

```
PS C:\Users\username> gem install jekyll
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/http_parser.rb-0.8.0/ext/ruby_http_parser
C:/tools/ruby31/bin/ruby.exe -I C:/tools/ruby31/lib/ruby/3.1.0 -r ./siteconf20221226-26976-2dk681.rb extconf.rb
creating Makefile

current directory: C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/http_parser.rb-0.8.0/ext/ruby_http_parser
make DESTDIR\= clean
current directory: C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/http_parser.rb-0.8.0/ext/ruby_http_parser
make DESTDIR\=
make failedNo such file or directory - make

Gem files will remain installed in C:/tools/ruby31/lib/ruby/gems/3.1.0/gems/http_parser.rb-0.8.0 for inspection.
Results logged to C:/tools/ruby31/lib/ruby/gems/3.1.0/extensions/x64-mingw-ucrt/3.1.0/http_parser.rb-0.8.0/gem_make.out
```

## What's the output from `ridk version`?
System details -- output from `ridk version`
```
PS C:\Users\username> ridk version
---
ruby:
  path: C:/tools/ruby31
  version: 3.1.2
  platform: x64-mingw-ucrt
  cc: gcc.exe (Rev10, Built by MSYS2 project) 11.2.0
ruby_installer:
  package_version: 3.1.2-1
  git_commit: 17502f9
msys2:
  path: C:\tools\msys64
sh: GNU bash, version 5.1.16(2)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19044.2364]
```
and from `$env:path -split ";"`
```
C:\tools\ruby31\bin
C:\Program Files (x86)\Common Files\Oracle\Java\javapath
C:\WINDOWS\system32
C:\WINDOWS
C:\WINDOWS\System32\Wbem
C:\WINDOWS\System32\WindowsPowerShell\v1.0\
C:\WINDOWS\System32\OpenSSH\
M:\pcraster-4.0.2_x86-64\bin
M:\pcraster-4.0.2_x86-64\python
C:\Program Files\Wolfram Research\WolframScript\
C:\Program Files\MiKTeX\miktex\bin\x64\
C:\Program Files\gs\gs9.56.1\bin
C:\Program Files\dotnet\
C:\ProgramData\chocolatey\bin
C:\Users\K2150648\AppData\Local\Ruby31-x64\bin
C:\Ruby31-x64\bin
C:\Users\K2150648\AppData\Local\Microsoft\WindowsApps
C:\Users\K2150648\AppData\Local\Programs\Git\cmd
C:\Users\K2150648\AppData\Local\gitkraken\bin
```

Happy to provide any further details needed.
