### ISSUE TITLE
Discussion: require takes XX times longer than on linux

### ISSUE THREAD

**Issue by Largo** [oneclick/rubyinstaller2#328]
_OT: Happy New Year to all contributors and thank you so much for all the work you do for us windows rubyists! RubyInstaller is a fantastic project and really important for the community. I'd donate, but I cannot find any donation information.
I live in Japan and if there's anything I could do, to help this project, for instance try to get funding from the Ruby Association, let me know!_

## Call for Feedback
For now, I'm most interested to know, if the rubyinstaller devs are aware of this and have already tried to improve this. And if there are any ideas on how to improve this and in which project (rubyinstaller, ruby, msys, windows itself). It's not a huge problem and so it's okay as it is, but it would be helpful for ruby scripts that are run in sequence.

## What problems are you experiencing?
Require take xx times longer than on linux. [If the gem has a lot of files](https://github.com/ruby-concurrency/concurrent-ruby/issues/971) like ruby-concurrent (dependecy of tzinfo), it takes up to 2 seconds on my machine.

From what I've researched, I assume it's the File IO, which is making it slow and not ruby itself.  
I heard stat is slow on windows, maybe it is something like that and we could replace the syscall for windows?

## Steps to reproduce

Tested on various different Windows 10-11 systems, with ruby 2.x to 3.2.

```
gem install tzinfo
gem install sqlite
```

```
irb(main):001:0> measure
TIME is added.
=> nil
irb(main):002:0> require 'sqlite'
processing time: 0.110246s
=> true
irb(main):003:0> require 'tzinfo'
processing time: 2.351778s
=> true
irb(main):006:0> require 'rexml'
processing time: 0.500891s
=> true
```

Sysinternal Process Monitor shows Events like QueryAllInformationFile and QueryInformationVolume, which might not be necessary. 

## What's the output from `ridk version`?
```
ruby:
  path: C:/Ruby32-x64
  version: 3.2.0
  platform: x64-mingw-ucrt
  cc: gcc.exe (Rev7, Built by MSYS2 project) 12.2.0
ruby_installer:
  package_version: 3.2.0-1
  git_commit: 5507d7c
msys2:
  path: C:\Ruby32-x64\msys64
cc: gcc (Rev6, Built by MSYS2 project) 12.2.0
sh: GNU bash, Version 5.2.9(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.22621.963]
```

related [slow ruby require concurent](https://github.com/ruby-concurrency/concurrent-ruby/issues/971)
