### ISSUE TITLE
Windows 10: Error installing Jekyll

### ISSUE THREAD

**Issue by TheVietScholar** [oneclick/rubyinstaller2#355]
## What problems are you experiencing?
Jekyll is failing to install

## Steps to reproduce
gem install jekyll bundler

```Building native extensions. This could take a while...
ERROR:  Error installing jekyll:
        ERROR: Failed to build gem native extension.

    current directory: C:/Users/Matthew Nguyen/.local/share/gem/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c
C:/Ruby32-x64/bin/ruby.exe extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi,/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/ffi,/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/usr/include/ffi... no
checking for whether -Wl,--exclude-libs,ALL is accepted as LDFLAGS... yes
checking for whether -pthread is accepted as LDFLAGS... yes
creating extconf.h
creating Makefile

current directory: C:/Users/Matthew Nguyen/.local/share/gem/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c
make DESTDIR\= sitearchdir\=./.gem.20230831-15532-q4tnks sitelibdir\=./.gem.20230831-15532-q4tnks clean

current directory: C:/Users/Matthew Nguyen/.local/share/gem/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c
make DESTDIR\= sitearchdir\=./.gem.20230831-15532-q4tnks sitelibdir\=./.gem.20230831-15532-q4tnks
generating ffi_c-x64-mingw-ucrt.def
/bin/sh: -c: line 1: syntax error near unexpected token `('
/bin/sh: -c: line 1: `mkdir -p "/c/Users/Matthew Nguyen/.local/share/gem/ruby/3.2.0/gems/ffi-1.15.5/ext/ffi_c/libffi-x64-mingw-ucrt" ""/c/Users/Matthew(D)"'
make: *** [libffi.mk:6: "/c/Users/Matthew] Error 2

make failed, exit code 2

Gem files will remain installed in C:/Users/Matthew Nguyen/.local/share/gem/ruby/3.2.0/gems/ffi-1.15.5 for inspection.
Results logged to C:/Users/Matthew Nguyen/.local/share/gem/ruby/3.2.0/extensions/x64-mingw-ucrt/3.2.0/ffi-1.15.5/gem_make.out
Fetching bundler-2.4.19.gem
Successfully installed bundler-2.4.19
Parsing documentation for bundler-2.4.19
Installing ri documentation for bundler-2.4.19
Done installing documentation for bundler after 0 seconds
1 gem installed
```
## What's the output from `ridk version`?
```
ruby:
  path: C:/Ruby32-x64
  version: 3.2.2
  platform: x64-mingw-ucrt
ruby_installer:
  package_version: 3.2.2-1
  git_commit: 83df213
msys2:
  path: C:\Ruby32-x64\msys64
cc: gcc (Rev10, Built by MSYS2 project) 12.2.0
sh: GNU bash, version 5.2.15(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.19045.3324]
```
