### ISSUE TITLE
Problems to work with Readline

### ISSUE THREAD

**Issue by deivid-rodriguez** [oneclick/rubyinstaller2#36]
I'm totally unsure whether this is a problem in rubyinstaller2 or just me doing something wrong, but since release is close, I figure it's better to make sure and help making the final release great :)

## What problems are you experiencing?

I'm having problems using `readline` via [byebug](https://github.com/deivid-rodriguez/byebug/).

## Steps to reproduce

I installed a virtual windows machine with virtualbox and then installed the `2.4.1-1rc2` via the exe file in the releases page. Then, I think I chose number 3 from the options about `ridk` installation... Now I open a terminal via "Start Command Prompt with Ruby" and do the following. 

```
git clone https://github.com/deivid-rodriguez/byebug
cd byebug
bundle
bundle exec rake
```

This sucessfully installs all depencies, sucessfully compiles byebug's C-extension (as part of `bundle exec rake`), but fails when requiring `byebug` to run the tests. This is the error:

```
    Sorry, you can't use byebug without Readline. To solve this, you need to
    rebuild Ruby with Readline support. If using Ubuntu, try `sudo apt-get
    install libreadline-dev` and then reinstall your Ruby.
rake aborted!
LoadError: cannot load such file -- readline
C:/Users/IEUser/byebug/lib/byebug/history.rb:2:in `require'
C:/Users/IEUser/byebug/lib/byebug/history.rb:2:in `<top (required)>'
C:/Users/IEUser/byebug/lib/byebug/interface.rb:2:in `require'
C:/Users/IEUser/byebug/lib/byebug/interface.rb:2:in `<top (required)>'
C:/Users/IEUser/byebug/lib/byebug/core.rb:5:in `require'
C:/Users/IEUser/byebug/lib/byebug/core.rb:5:in `<top (required)>'
C:/Users/IEUser/byebug/test/support/test_case.rb:3:in `require'
C:/Users/IEUser/byebug/test/support/test_case.rb:3:in `<top (required)>'
C:/Users/IEUser/byebug/test/test_helper.rb:2:in `require'
C:/Users/IEUser/byebug/test/test_helper.rb:2:in `<top (required)>'
C:/Users/IEUser/byebug/test/commands/break_test.rb:1:in `require'
C:/Users/IEUser/byebug/test/commands/break_test.rb:1:in `<top (required)>'
C:/Users/IEUser/byebug/script/minitest_runner.rb:17:in `require'
C:/Users/IEUser/byebug/script/minitest_runner.rb:17:in `block in run'
C:/Users/IEUser/byebug/script/minitest_runner.rb:17:in `each'
C:/Users/IEUser/byebug/script/minitest_runner.rb:17:in `run'
C:/Users/IEUser/byebug/Rakefile:47:in `block in <top (required)>'
Tasks: TOP => default => test

``` 

I grepped commits with `readline` and found:

* https://github.com/oneclick/rubyinstaller2/commit/8fc194fb2b89478d49b242770f9b93397732d191. I see that the related issue was closed after the change, so maybe readline 7.0 works again?

* https://github.com/oneclick/rubyinstaller2/commit/a2ec247dc0c4a4c698819296deb1635c327bb9a7. Here it seems that `rb-readline` will be provided as a default gem or something instead of the "c-ext based" one. If I add `rb-readline` to the `Gemfile`, it all works as expected, but shouldn't this be provided by default?

## What's the output from `ridk version`?

```
C:\Users\IEUser\byebug>ridk version
---
ruby:
  path: C:/Ruby24
  version: 2.4.1
  platform: i386-mingw32
ruby_installer:
  package_version: 2.4.1-1rc2
  git_commit: 1b324f5
msys2:
  path: C:\msys32
  title: MSYS2 32bit
  version: '20161025'
cc: i686-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 6.3.0
sh: GNU bash, version 4.3.46(2)-release (i686-pc-msys)
```

Thanks for your help!
