### ISSUE TITLE
Failed to override the executable when executing `gem update rdoc`.

### ISSUE THREAD

**Issue by taroxd** [oneclick/rubyinstaller2#41]
## What problems are you experiencing?
Failed to override the executable when executing `gem update`.
When I am prompted whether to overwrite the executable, I cannot type `y` to the command prompt.
My OS is Windows 10 Build 16199 in Simplified Chinese.

![image](https://cloud.githubusercontent.com/assets/6070540/26478800/5e797b8a-4201-11e7-95f4-bd7a86e76afa.png)

## Steps to reproduce
I have no idea what to do other than calling `gem install rdoc`.

## What's the output from `ridk version`?
```
ruby:
  path: D:/local/Ruby/stable
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-1
  git_commit: 6635d31
msys2:
  path: D:\local\msys64
cc: x86_64-w64-mingw32-gcc (Rev3, Built by MSYS2 project) 6.3.0
sh: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
```
