### ISSUE TITLE
`rubyinstaller-head-arm` missing `libwinpthread-1.dll`

### ISSUE THREAD

**Issue by ntkme** [oneclick/rubyinstaller2#434]
> Error: The process 'C:\rubyinstaller-head-arm\bin\ruby.exe' failed with exit code 3221225785

I'm using `ruby/setup-ruby`.

If I set `windows-toolchain: none` option (meaning no msys2/ridk), I get the error above and it seems exit code 3221225785 means missing DLLs. On the other hand, with msys2 installation added to PATH it works fine.

The expectation is that basic ruby features should work without installing msys2.

``` yaml

on:
  push:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [windows-11-arm]
        ruby-version: [ruby, head]
        windows-toolchain: [default, none]
    steps:
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby-version }}
          windows-toolchain: ${{ matrix.windows-toolchain }}
```
