### ISSUE TITLE
mingw-w64 unrecognized when installing gems

### ISSUE THREAD

**Issue by npomf** [oneclick/rubyinstaller2#44]
## What problems are you experiencing?

When attempting to `gem install` a gem that requires building C-extension code, the build environment provided by mingw-w64 (installed from a separate project) is unusable or unrecognized.  However, the `ridk version` command correctly displays the GCC compiler shipped with mingw.

The environment appears to work outside of Ruby, as it successfully built and installed the Nimble package manager.

## Steps to reproduce

This is being done on a Windows 7 64-bit machine.

```
C:\arbitrary\path> gem install json
MSYS2 could not be found. Please run 'ridk install'
or download and install MSYS2 manually from https://msys2.github.io/
```

## What's the output from `ridk version`?

```yaml
---
ruby:
  path: D:/Ruby
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-1
  git_commit: 6635d31
cc: x86_64-w64-mingw32-gcc (x86_64-win32-seh-rev1, Built by MinGW-W64 project) 6.3.0
```
