### ISSUE TITLE
File.mtime doesn't return milliseconds

### ISSUE THREAD

**Issue by AlexWayfer** [oneclick/rubyinstaller2#52]
## What problems are you experiencing?

No milliseconds from `File.mtime`.

## Steps to reproduce

```ruby
File.exist?('env') #=> true
File.mtime('env').usec #=> 0 <- zero!
```

From Bash on Windows:

```ruby
File.mtime('env').usec #=> 483623
```

## What's the output from `ridk version`?

```
>ridk version
---
ruby:
  path: C:/Ruby24-x64
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-1
  git_commit: 6635d31
msys2:
  path: C:\msys64
  title: MSYS2 64bit
  version: '20161025'
sh: GNU bash, version 4.3.46(2)-release (x86_64-pc-msys)
```

## Additional thoughts

1. I think, [oneclick/rubyinstaller](https://github.com/oneclick/rubyinstaller) has the same problem, and I hope that I should not write the same there for fixing.
2. A similar problems: [jruby/issues/4520](https://github.com/jruby/jruby/issues/4520), [rubinius/issues/3502](https://github.com/rubinius/rubinius/issues/3502).
3. Specs for this: [ruby/spec/pull/386](https://github.com/ruby/spec/pull/386).
