### ISSUE TITLE
Setup wizard checkboxes have no tooltips despite there being a mouse-over tip

### ISSUE THREAD

**Issue by BoffinbraiN** [oneclick/rubyinstaller2#61]
## Steps to reproduce

When installing Ruby, progress to the Installation Destination and Optional Tasks stage.

There is a label here that says 'TIP: Mouse over the above options for more detailed information'. However, none of the the controls show tooltips when moused over. Screenshot is attached. 

![nomouseover](https://user-images.githubusercontent.com/13255058/28823448-809b37ba-76b5-11e7-8fc1-b4ef8b00ebf3.png)

## What's the output from `ridk version`?

```
ruby:
  path: C:/Ruby24-x64
  version: 2.4.1
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.1-2
  git_commit: a2667ee
```
