### ISSUE TITLE
The specified module could not be found ruby_filemagic.so

### ISSUE THREAD

**Issue by ShockwaveNN** [oneclick/rubyinstaller2#64]
## What problems are you experiencing?
Tried to use `ruby-filemagic` gem
It fails with:
```
The specified module could not be found.   - C:/Ruby24/lib/ruby/gems/2.4.0/gems/ruby-filemagic-0.7.2-x86-mingw32/lib/filemagic/2.4/ruby_filemagic.so
```
But file `C:/Ruby24/lib/ruby/gems/2.4.0/gems/ruby-filemagic-0.7.2-x86-mingw32/lib/filemagic/2.4/ruby_filemagic.so` exists. 
Maybe some problems with PATH?

## Steps to reproduce
1. `git clone https://github.com/ONLYOFFICE/ooxml_parser`
2. `bundle install`
3. `rspec`

## What's the output from `ridk version`?
---
```
ruby:
  path: C:/Ruby24
  version: 2.4.1
  platform: i386-mingw32
ruby_installer:
  package_version: 2.4.1-2
  git_commit: a2667ee
msys2:
  path: C:\msys32
  title: MSYS2 32bit
  version: '20161025'
cc: i686-w64-mingw32-gcc (Rev2, Built by MSYS2 project) 7.1.0
sh: GNU bash, version 4.4.12(1)-release (i686-pc-msys)
```
