### ISSUE TITLE
msys 403 error

### ISSUE THREAD

**Issue by djm158** [oneclick/rubyinstaller2#99]
## What problems are you experiencing?

`ridk install` fails because my firewall blocks repo.mys2.org downloads.

## Steps to reproduce

`ridk install`

## What's the output from `ridk version`?
```
ruby:
  path: C:/Ruby24-x64
  version: 2.4.3
  platform: x64-mingw32
ruby_installer:
  package_version: 2.4.3-1
  git_commit: 36aac73
msys2:
  path: C:\msys64
  title: MSYS2 64bit
  version: '20170918'
sh: GNU bash, version 4.4.12(1)-release (x86_64-pc-msys)
os: Microsoft Windows [Version 10.0.16299.248]
```

I was able to work around this by manually installing the latest msys2 from the latest executable here: 
https://sourceforge.net/projects/msys2/files/?source=navbar

I thought it might be worth documenting this in case any one else had this issue.
